// ═══════════════════════════════════════════════════════════════
// CLOCK
// ═══════════════════════════════════════════════════════════════
function updateClock() {
  const now = new Date();
  const p = n => String(n).padStart(2,'0');
  document.getElementById('atl-clock').textContent =
    p(now.getUTCHours())+':'+p(now.getUTCMinutes())+':'+p(now.getUTCSeconds())+' UTC';
}
setInterval(updateClock, 1000);
updateClock();

// ═══════════════════════════════════════════════════════════════
// COPY TRADE IDEA — CLIPBOARD FORMATTERS
// ═══════════════════════════════════════════════════════════════
function _copyFlash(btn, label) {
  btn.classList.add('success');
  btn.textContent = '✓ COPIED';
  setTimeout(() => { btn.classList.remove('success'); btn.textContent = label; }, 1800);
}

async function _copyToClipboard(text, btn, label) {
  try {
    await navigator.clipboard.writeText(text);
    _copyFlash(btn, label);
  } catch(e) {
    const ta = document.createElement('textarea');
    ta.value = text; ta.style.position = 'fixed'; ta.style.opacity = '0';
    document.body.appendChild(ta); ta.select();
    document.execCommand('copy');
    document.body.removeChild(ta);
    _copyFlash(btn, label);
  }
}

function copyPrimaryTrade(d) {
  if (!d || d.tradeRejected) return;
  const pl = d.primaryLevels;
  const dir = d.primaryDir;
  const isLong = dir === 'LONG';
  const conviction = d.weightedScore > 75 ? 'HIGH' : d.weightedScore >= 55 ? 'MED' : 'LOW';
  const smcChecks = [
    d.lastTrend === (isLong ? 1 : -1) ? '✓ SuperTrend aligned' : '· SuperTrend opposing',
    (isLong ? d.inDiscount : d.inPremium) ? '✓ Price in ' + (isLong ? 'Discount' : 'Premium') : '· Price not at ideal zone',
    d.struct && (isLong ? (d.struct.recentBOS_up || d.struct.recentCHOCH_up) : (d.struct.recentBOS_down || d.struct.recentCHOCH_down)) ? '✓ BOS/CHoCH confirmed' : '· No structure break',
    (d.rsi !== null && (isLong ? d.rsi < 55 : d.rsi > 45)) ? `✓ RSI aligned (${d.rsi ? d.rsi.toFixed(1) : '—'})` : `· RSI neutral (${d.rsi ? d.rsi.toFixed(1) : '—'})`,
    d.tqi > 0.5 ? `✓ TQI strong (${d.tqi.toFixed(2)})` : `· TQI weak (${d.tqi.toFixed(2)})`,
    (isLong ? d.funding < -0.01 : d.funding > 0.02) ? `✓ Funding edge (${(d.funding||0).toFixed(4)}%)` : `· Funding neutral (${(d.funding||0).toFixed(4)}%)`,
    (isLong ? d.lsRatio < 0.8 : d.lsRatio > 1.2) ? `✓ L/S crowded for trade (${(d.lsRatio||1).toFixed(2)})` : `· L/S neutral (${(d.lsRatio||1).toFixed(2)})`,
  ].join('\n  ');

  const lines = [
    `╔══════════════════════════════════════════╗`,
    `  ATL · TRADE IDEA  |  ${_lastTradeData?.ticker || ''}USDT  ·  ${(_lastTradeData?.tf || '').toUpperCase()}  ·  ${(_lastTradeData?.timestamp||'').slice(0,16).replace('T',' ')} UTC`,
    `╚══════════════════════════════════════════╝`,
    ``,
    `  DIRECTION    ${isLong ? '▲ LONG' : '▼ SHORT'}`,
    `  CONVICTION   ${conviction} (${d.weightedScore}%)`,
    `  BIAS         BULL ${d.bullPct}%  vs  BEAR ${100-d.bullPct}%`,
    `  CONFIDENCE   ${d.confidenceLabel}`,
    ``,
    `  ── LEVELS ─────────────────────────────`,
    `  ENTRY         ${fmtPrice(pl.entry)}    ${isLong ? ((_lastTradeData && _lastTradeData.currentPrice < pl.entry * 1.005) ? '← WAIT FOR PULLBACK' : '● IN ZONE') : ((_lastTradeData && _lastTradeData.currentPrice > pl.entry * 0.995) ? '← WAIT FOR RALLY' : '● IN ZONE')}`,
    `  STOP LOSS     ${fmtPrice(pl.sl)}`,
    `  TP 1          ${fmtPrice(pl.tp1)}`,
    `  TP 2          ${fmtPrice(pl.tp2)}`,
    `  RISK·REWARD   ${pl.rr}R`,
    `  RISK $        ${fmtPrice(Math.abs(pl.entry - pl.sl))} per unit`,
    ``,
    `  ── SMC CONFLUENCE ──────────────────────`,
    `  ${smcChecks}`,
    ``,
    `  ── ANALYSIS ────────────────────────────`,
    `  ${(d.primaryNarr || '').replace(/\. /g, '.\n  ')}`,
    ``,
    `  ─────────────────────────────────────────`,
    `  Generated by ATL · Market Intelligence Terminal`,
  ].join('\n');

  return lines;
}

function copyQuickTrade(d) {
  if (!d || d.tradeRejected) return;
  const pl = d.primaryLevels;
  const dir = d.primaryDir;
  const conviction = d.weightedScore > 75 ? 'HIGH' : d.weightedScore >= 55 ? 'MED' : 'LOW';
  return [
    `${dir === 'LONG' ? '▲ LONG' : '▼ SHORT'} ${_lastTradeData?.ticker || ''}USDT  [${(_lastTradeData?.tf||'').toUpperCase()}]  ${conviction} CONVICTION (${d.weightedScore}%)`,
    `Entry: ${fmtPrice(pl.entry)}  |  SL: ${fmtPrice(pl.sl)}  |  TP1: ${fmtPrice(pl.tp1)}  |  TP2: ${fmtPrice(pl.tp2)}  |  RR: ${pl.rr}R`,
    `Bias: BULL ${d.bullPct}% vs BEAR ${100-d.bullPct}%  ·  ${(_lastTradeData?.timestamp||'').slice(0,16).replace('T',' ')} UTC  ·  ATL · Market Intelligence Terminal`,
  ].join('\n');
}

function copyAnalysisOnly(d) {
  if (!d) return;
  const ticker = _lastTradeData?.ticker || '';
  const tf = (_lastTradeData?.tf || '').toUpperCase();
  const ts = (_lastTradeData?.timestamp||'').slice(0,16).replace('T',' ');
  if (d.tradeRejected) {
    return `ATL ANALYSIS — ${ticker}USDT ${tf} — ${ts} UTC\n\nSETUP REJECTED — NO TRADE\nReason: ${(d.tradeDecisionReason||'INVALID_SETUP').replace(/_/g,' ')}\n\nBias: BULL ${d.bullPct}% vs BEAR ${100-d.bullPct}%\nWaiting for valid confluence before entry.\n\n— ATL · Market Intelligence Terminal`;
  }
  return `ATL ANALYSIS — ${ticker}USDT ${tf} — ${ts} UTC\n\nBIAS: ${d.primaryDir === 'LONG' ? 'BULLISH' : 'BEARISH'} (${d.weightedScore}% confidence)\n\n${d.primaryNarr}\n\n— ATL · Market Intelligence Terminal`;
}

function injectCopyBar(cardEl, cardType, data) {
  if (!cardEl) return;
  cardEl.querySelectorAll('.copy-bar').forEach(b => b.remove());
  const bar = document.createElement('div');
  bar.className = 'copy-bar';

  if (cardType === 'primary') {
    const btnFull = document.createElement('button');
    btnFull.className = 'copy-btn primary-copy';
    btnFull.innerHTML = '⎘ COPY TRADE IDEA';
    btnFull.addEventListener('click', e => {
      e.stopPropagation();
      const text = copyPrimaryTrade(data);
      if (text) _copyToClipboard(text, btnFull, '⎘ COPY TRADE IDEA');
    });

    const btnQuick = document.createElement('button');
    btnQuick.className = 'copy-btn';
    btnQuick.innerHTML = '⎘ QUICK COPY';
    btnQuick.title = 'One-line summary with levels';
    btnQuick.addEventListener('click', e => {
      e.stopPropagation();
      const text = copyQuickTrade(data);
      if (text) _copyToClipboard(text, btnQuick, '⎘ QUICK COPY');
    });

    const btnAnalysis = document.createElement('button');
    btnAnalysis.className = 'copy-btn';
    btnAnalysis.innerHTML = '⎘ ANALYSIS';
    btnAnalysis.title = 'Copy narrative analysis only';
    btnAnalysis.addEventListener('click', e => {
      e.stopPropagation();
      const text = copyAnalysisOnly(data);
      if (text) _copyToClipboard(text, btnAnalysis, '⎘ ANALYSIS');
    });

    bar.appendChild(btnFull);
    bar.appendChild(btnQuick);
    bar.appendChild(btnAnalysis);
  } else {
    const btn = document.createElement('button');
    btn.className = 'copy-btn';
    btn.innerHTML = '⎘ COPY COUNTER SETUP';
    btn.addEventListener('click', e => {
      e.stopPropagation();
      const cl = data.counterLevels;
      const dir = data.counterTxt;
      const text = [
        `COUNTER ${dir} — ${_lastTradeData?.ticker || ''}USDT [${(_lastTradeData?.tf||'').toUpperCase()}] LOW CONVICTION`,
        `Entry: ${fmtPrice(cl.entry)}  |  SL: ${fmtPrice(cl.sl)}  |  TP1: ${fmtPrice(cl.tp1)}  |  TP2: ${fmtPrice(cl.tp2)}`,
        `${data.counterNarr}`,
        `— ATL · Market Intelligence Terminal  ·  ${(_lastTradeData?.timestamp||'').slice(0,16).replace('T',' ')} UTC`,
      ].join('\n');
      _copyToClipboard(text, btn, '⎘ COPY COUNTER SETUP');
    });
    bar.appendChild(btn);
  }
  cardEl.appendChild(bar);
}

// Wrap updateTradeIdeas to inject copy bars after render
const _origUpdateTradeIdeas = updateTradeIdeas;
updateTradeIdeas = function(data) {
  _origUpdateTradeIdeas(data);
  if (data.tradeRejected) {
    const wrap = document.getElementById('scenarios-wrap');
    if (wrap) {
      const existingBar = wrap.querySelector('.copy-bar');
      if (!existingBar) {
        const bar = document.createElement('div');
        bar.className = 'copy-bar';
        bar.style.padding = '0 12px 10px';
        const btn = document.createElement('button');
        btn.className = 'copy-btn';
        btn.innerHTML = '⎘ COPY REJECTION REPORT';
        btn.addEventListener('click', e => {
          e.stopPropagation();
          const text = copyAnalysisOnly(data);
          if (text) _copyToClipboard(text, btn, '⎘ COPY REJECTION REPORT');
        });
        bar.appendChild(btn);
        wrap.appendChild(bar);
      }
    }
    return;
  }
  const cards = document.querySelectorAll('#scenarios-wrap .trade-card');
  cards.forEach((card, i) => {
    if (card.style.borderColor && card.style.borderColor.includes('255, 165')) return;
    if (i === 0) injectCopyBar(card, 'primary', data);
    else if (i === 1) injectCopyBar(card, 'counter', data);
  });
};

// ═══════════════════════════════════════════════════════════════
// AUTO REFRESH
// ═══════════════════════════════════════════════════════════════
function startAutoRefresh() {
  stopAutoRefresh();
  const secs = parseInt(document.getElementById('refreshIntervalSel').value) * 1000;
  _autoTimer = setInterval(() => { if (_lastTicker) runAnalysis(); }, secs);
}
function stopAutoRefresh() {
  if (_autoTimer) { clearInterval(_autoTimer); _autoTimer = null; }
}
function setAutoRefresh(on) {
  _autoOn = on;
  const btn = document.getElementById('autoRefreshBtn');
  btn.textContent = _autoOn ? 'ON' : 'OFF';
  btn.className   = _autoOn ? 'on' : '';
  document.getElementById('rail-refresh').style.color = _autoOn ? 'var(--green)' : '';
  _autoOn ? startAutoRefresh() : stopAutoRefresh();
}

// ═══════════════════════════════════════════════════════════════
// HELP MODAL CONTENT
// ═══════════════════════════════════════════════════════════════
const HM_CONTENT = {
  basics: `
    <div class="hm-section-title">What is this tool?</div>
    <div class="hm-def"><div class="hm-def-key">ATL Terminal</div><div class="hm-def-val">A professional market analysis tool for crypto futures. Enter any coin symbol and get a full breakdown — trend, key price levels, and a suggested trade with entry, stop loss, and targets.</div></div>
    <div class="hm-def"><div class="hm-def-key">Analysis Page</div><div class="hm-def-val">Type any coin symbol (like BTC, ETH, SOL) and the tool will give you a full breakdown — trend, key price levels, and a suggested trade with entry, stop loss, and targets.</div></div>
    <div class="hm-section-title">Key Concepts (Plain English)</div>
    <div class="hm-def"><div class="hm-def-key">Bullish</div><div class="hm-def-val">The analysis expects the price to go <b>up</b>. Signals suggest buying (going LONG).</div></div>
    <div class="hm-def"><div class="hm-def-key">Bearish</div><div class="hm-def-val">The analysis expects the price to go <em>down</em>. Signals suggest selling (going SHORT).</div></div>
    <div class="hm-def"><div class="hm-def-key">Long</div><div class="hm-def-val">A trade that profits when price goes <b>up</b>. You're betting the coin rises.</div></div>
    <div class="hm-def"><div class="hm-def-key">Short</div><div class="hm-def-val">A trade that profits when price goes <em>down</em>. You're betting the coin falls.</div></div>
    <div class="hm-def"><div class="hm-def-key">Timeframe (TF)</div><div class="hm-def-val">The period of each candle on the chart. <b>1W</b> = weekly (slow, big picture). <b>1D</b> = daily. <b>4H</b> = four hours. <b>1H</b> = one hour. <b>15m / 5m</b> = short-term. Longer timeframes = stronger, more reliable signals.</div></div>
    <div class="hm-note">💡 Tip: If you're new to trading, start with the 4H or 1D timeframe. These are slower and easier to manage than 5m or 15m.</div>
  `,
  signals: `
    <div class="hm-section-title">What the signals mean</div>
    <div class="hm-def"><div class="hm-def-key">SuperTrend</div><div class="hm-def-val">The simplest trend signal. <b>BULLISH</b> = price is above the trend line and going up. <em>BEARISH</em> = price is below and going down. When this flips, the market is changing direction.</div></div>
    <div class="hm-def"><div class="hm-def-key">BOS</div><div class="hm-def-val"><b>Break of Structure.</b> The price broke a previous high (bullish) or low (bearish). This confirms the trend continues. A bullish BOS is a green signal for longs.</div></div>
    <div class="hm-def"><div class="hm-def-key">CHoCH</div><div class="hm-def-val"><b>Change of Character.</b> The first sign a trend might be reversing. Price broke in the opposite direction for the first time. Not confirmed yet — but worth watching.</div></div>
    <div class="hm-def"><div class="hm-def-key">Fair Value Gap</div><div class="hm-def-val">A price gap caused by fast movement where little real trading happened. The market tends to come back and fill these gaps. <b>Good entry zones</b> for trades.</div></div>
    <div class="hm-def"><div class="hm-def-key">Order Block</div><div class="hm-def-val">A zone where big institutions placed large orders. Price often bounces from these areas. <b>BULL OB</b> = support zone. <b>BEAR OB</b> = resistance zone.</div></div>
    <div class="hm-def"><div class="hm-def-key">Premium Zone</div><div class="hm-def-val">Top 25% of the price range. <b>Price here is expensive</b> — better to sell or wait for a dip before buying.</div></div>
    <div class="hm-def"><div class="hm-def-key">Discount Zone</div><div class="hm-def-val">Bottom 25% of the price range. <b>Price here is cheap</b> relative to the range — better zone to buy.</div></div>
    <div class="hm-def"><div class="hm-def-key">Liquidity Sweep</div><div class="hm-def-val">Price briefly dipped below a key low (or above a key high) to trigger stop-losses, then reversed. <b>Often signals a strong reversal</b> in the opposite direction.</div></div>
    <div class="hm-def"><div class="hm-def-key">Breakout</div><div class="hm-def-val">Price pushed through a key resistance or support level. Suggests a <b>strong directional move</b> is starting.</div></div>
    <div class="hm-note">💡 The strongest trades have multiple signals agreeing. BOS + discount zone + bullish SuperTrend all at once is much stronger than just one signal alone.</div>
  `,
  numbers: `
    <div class="hm-section-title">Understanding the numbers</div>
    <div class="hm-def"><div class="hm-def-key">Confidence %</div><div class="hm-def-val"><b>70%+ = High conviction.</b> 55–69% = Medium. Below 55% = Low. Higher % means more signals pointing the same way.</div></div>
    <div class="hm-def"><div class="hm-def-key">Risk · Reward (R)</div><div class="hm-def-val">How much you stand to gain vs lose. <b>3R means for every $1 you risk, you could make $3.</b> Always aim for at least 2R.</div></div>
    <div class="hm-def"><div class="hm-def-key">RSI (14)</div><div class="hm-def-val">Measures buying and selling pressure. <b>Below 30</b> = heavily sold, may bounce. <b>Above 70</b> = heavily bought, may pull back.</div></div>
    <div class="hm-def"><div class="hm-def-key">EFF. Ratio</div><div class="hm-def-val">How cleanly price is moving. <b>0.7+ = clean trend.</b> <em>Below 0.3 = choppy</em>, just noise.</div></div>
    <div class="hm-def"><div class="hm-def-key">Trend QI</div><div class="hm-def-val">Overall grade for the trend. <b>HIGH (0.6+)</b> = clear strong trend. <em>LOW (below 0.4)</em> = weak or unclear.</div></div>
    <div class="hm-def"><div class="hm-def-key">Funding Rate</div><div class="hm-def-val"><b>Positive = longs paying</b> (market over-crowded long, reversal risk). <em>Negative = shorts paying</em> (market may squeeze up).</div></div>
    <div class="hm-def"><div class="hm-def-key">L/S Ratio</div><div class="hm-def-val"><b>Above 1.5</b> = very crowded longs (risky to be long). <em>Below 0.7</em> = very crowded shorts (risky to be short).</div></div>
    <div class="hm-def"><div class="hm-def-key">ATR</div><div class="hm-def-val">Average True Range — the average daily price movement. Use 1–2× ATR as your minimum stop distance.</div></div>
    <div class="hm-note">💡 Don't chase high confidence alone. A 90% confidence on a BEARISH coin means it's a strong short — not a buy. Always check direction (▲ or ▼).</div>
  `,
  howto: `
    <div class="hm-section-title">Step-by-step: How to analyse a coin</div>
    <div class="hm-def"><div class="hm-def-key">Step 1</div><div class="hm-def-val"><b>Type a ticker</b> — enter any coin symbol like BTC, ETH, SOL in the input box. Choose your timeframe (4H or 1D recommended for beginners).</div></div>
    <div class="hm-def"><div class="hm-def-key">Step 2</div><div class="hm-def-val"><b>Run Analysis</b> — click the ANALYSE button or press Enter. The tool fetches live data and computes everything.</div></div>
    <div class="hm-def"><div class="hm-def-key">Step 3</div><div class="hm-def-val"><b>Read the Trade Scenarios</b> — check the right-hand panel for PRIMARY trade direction, entry, stop loss, and TP targets.</div></div>
    <div class="hm-def"><div class="hm-def-key">Step 4</div><div class="hm-def-val"><b>Check the SMC Checklist</b> — the more green ticks (✓), the stronger the setup. Fewer than 3 ticks = be cautious.</div></div>
    <div class="hm-def"><div class="hm-def-key">Step 5</div><div class="hm-def-val"><b>Wait for entry</b> — if it says "NOT YET — WAIT FOR PRICE TO REACH ENTRY", be patient. Don't chase price.</div></div>
    <div class="hm-section-title">Mistakes to avoid</div>
    <div class="hm-def"><div class="hm-def-key">Chasing price</div><div class="hm-def-val">Don't enter just because it's moving fast. Entering at the wrong level ruins your risk-reward ratio.</div></div>
    <div class="hm-def"><div class="hm-def-key">Skipping the SL</div><div class="hm-def-val">The Stop Loss is not optional. Always place it. One trade without a stop can wipe out many good ones.</div></div>
    <div class="hm-def"><div class="hm-def-key">Trading rejections</div><div class="hm-def-val">If you see "SETUP REJECTED — NO TRADE", don't force it. Move on and find a cleaner coin.</div></div>
    <div class="hm-note">💡 The best traders take fewer, higher-quality trades. Wait for HIGH conviction setups.</div>
  `
};

function renderHelpModal(tab) {
  document.getElementById('hm-body').innerHTML = HM_CONTENT[tab] || '';
  document.querySelectorAll('.hm-tab').forEach(t => t.classList.toggle('active', t.dataset.hmtab === tab));
}

// ═══════════════════════════════════════════════════════════════
// EVENT LISTENERS
// ═══════════════════════════════════════════════════════════════
document.getElementById('rail-refresh').addEventListener('click', () => setAutoRefresh(!_autoOn));

// ── CENTRAL STAGE SWITCHER — single source of truth ──────────
// Every rail icon and every "ANALYSE →" button calls this.
// No other file should touch stage display directly.
const ALL_STAGES = ['stage-analysis','stage-smc-scanner','stage-mit-scan','stage-btc-scan'];
const ALL_RAILS  = ['rail-analysis','rail-smc-scanner','rail-mit-scan','rail-btc-scan'];

function switchToStage(stageId, railId) {
  ALL_STAGES.forEach(id => {
    const el = document.getElementById(id);
    if (el) el.style.display = 'none';
  });
  ALL_RAILS.forEach(id => {
    const el = document.getElementById(id);
    if (el) el.classList.remove('active');
  });
  const stage = document.getElementById(stageId);
  if (stage) stage.style.display = 'flex';
  const rail = document.getElementById(railId);
  if (rail) rail.classList.add('active');
  // Sync mobile bottom rail
  const mobileMap = {
    'stage-analysis':    'mbr-analysis',
    'stage-smc-scanner': 'mbr-smc',
    'stage-mit-scan':    'mbr-mit',
    'stage-btc-scan':    'mbr-btc',
  };
  document.querySelectorAll('.mbr-btn').forEach(b => b.classList.remove('active'));
  const mbrId = mobileMap[stageId];
  if (mbrId) {
    const mbr = document.getElementById(mbrId);
    if (mbr) mbr.classList.add('active');
  }
}

document.getElementById('rail-analysis').addEventListener('click', () => {
  switchToStage('stage-analysis', 'rail-analysis');
  document.getElementById('tickerInput').focus();
});

// Analysis controls
document.getElementById('analysisBtn').addEventListener('click', runAnalysis);
document.getElementById('tickerInput').addEventListener('keydown', e => { if (e.key === 'Enter') runAnalysis(); });
document.querySelectorAll('.tf-pill').forEach(btn => {
  btn.addEventListener('click', () => {
    document.getElementById('tickerInput').value = btn.dataset.ticker;
    runAnalysis();
  });
});
document.addEventListener('keydown', e => {
  if (e.key === 'r' && !e.ctrlKey && document.activeElement.tagName !== 'INPUT') runAnalysis();
});

// Auto refresh button
document.getElementById('autoRefreshBtn').addEventListener('click', () => setAutoRefresh(!_autoOn));
document.getElementById('refreshIntervalSel').addEventListener('change', () => { if (_autoOn) startAutoRefresh(); });

// Mobile panel tabs
document.querySelectorAll('.mpt-btn').forEach(btn => {
  btn.addEventListener('click', () => {
    document.querySelectorAll('.mpt-btn').forEach(b => b.classList.remove('active'));
    btn.classList.add('active');
    const panel = btn.dataset.panel;
    document.getElementById('panel-deriv').classList.remove('mobile-active');
    document.getElementById('panel-trade').classList.remove('mobile-active');
    if (panel === 'deriv') document.getElementById('panel-deriv').classList.add('mobile-active');
    else if (panel === 'trade') document.getElementById('panel-trade').classList.add('mobile-active');
  });
});

// Resize — redraw chart
window.addEventListener('resize', () => {
  if (_lastChartState) {
    const { candles, stData, fvgs, swings, srLevels } = _lastChartState;
    renderChart(candles, stData, fvgs, swings, srLevels);
  }
});

// Panel help popovers
document.querySelectorAll('.panel-help-btn').forEach(btn => {
  btn.addEventListener('click', function(e) {
    e.stopPropagation();
    const targetId = this.dataset.popover;
    const pop = document.getElementById(targetId);
    if (!pop) return;
    const isOpen = pop.classList.contains('open');
    document.querySelectorAll('.panel-popover.open').forEach(p => p.classList.remove('open'));
    document.querySelectorAll('.panel-help-btn.active').forEach(b => b.classList.remove('active'));
    if (!isOpen) {
      pop.classList.add('open');
      this.classList.add('active');
    }
  });
});
document.addEventListener('click', e => {
  if (!e.target.closest('.panel-help-btn') && !e.target.closest('.panel-popover')) {
    document.querySelectorAll('.panel-popover.open').forEach(p => p.classList.remove('open'));
    document.querySelectorAll('.panel-help-btn.active').forEach(b => b.classList.remove('active'));
  }
});

// Help modal
document.getElementById('rail-help').addEventListener('click', () => {
  document.getElementById('help-modal-overlay').classList.add('open');
  renderHelpModal('basics');
});

document.addEventListener('DOMContentLoaded', () => {
  const overlay = document.getElementById('help-modal-overlay');
  const closeBtn = document.getElementById('hm-close-btn');
  if (closeBtn) closeBtn.addEventListener('click', () => overlay.classList.remove('open'));
  if (overlay) overlay.addEventListener('click', function(e) {
    if (e.target === this) this.classList.remove('open');
  });
  document.querySelectorAll('.hm-tab').forEach(tab => {
    tab.addEventListener('click', () => renderHelpModal(tab.dataset.hmtab));
  });
});
